const e = globalThis.Vue, {
  BaseTransition: t,
  BaseTransitionPropsValidators: o,
  Comment: r,
  EffectScope: n,
  ErrorCodes: s,
  ErrorTypeStrings: i,
  Fragment: a,
  KeepAlive: c,
  ReactiveEffect: l,
  Static: d,
  Suspense: p,
  Teleport: m,
  Text: u,
  TrackOpTypes: f,
  Transition: h,
  TransitionGroup: S,
  TriggerOpTypes: R,
  VueElement: y,
  assertNumber: C,
  callWithAsyncErrorHandling: v,
  callWithErrorHandling: g,
  camelize: T,
  capitalize: w,
  cloneVNode: E,
  compatUtils: x,
  compile: M,
  computed: V,
  createApp: k,
  createBlock: P,
  createCommentVNode: D,
  createElementBlock: A,
  createElementVNode: B,
  createHydrationRenderer: N,
  createPropsRestProxy: O,
  createRenderer: H,
  createSSRApp: I,
  createSlots: U,
  createStaticVNode: b,
  createTextVNode: z,
  createVNode: F,
  customRef: K,
  defineAsyncComponent: W,
  defineComponent: j,
  defineCustomElement: q,
  defineEmits: G,
  defineExpose: L,
  defineModel: Q,
  defineOptions: J,
  defineProps: X,
  defineSSRCustomElement: Y,
  defineSlots: Z,
  effect: _,
  effectScope: $,
  getCurrentInstance: ee,
  getCurrentScope: te,
  getCurrentWatcher: oe,
  getTransitionRawChildren: re,
  guardReactiveProps: ne,
  h: se,
  handleError: ie,
  hasInjectionContext: ae,
  hydrate: ce,
  hydrateOnIdle: le,
  hydrateOnInteraction: de,
  hydrateOnMediaQuery: pe,
  hydrateOnVisible: me,
  initCustomFormatter: ue,
  initDirectivesForSSR: fe,
  inject: he,
  isMemoSame: Se,
  isProxy: Re,
  isReactive: ye,
  isReadonly: Ce,
  isRef: ve,
  isRuntimeOnly: ge,
  isShallow: Te,
  isVNode: we,
  markRaw: Ee,
  mergeDefaults: xe,
  mergeModels: Me,
  mergeProps: Ve,
  nextTick: ke,
  nodeOps: Pe,
  normalizeClass: De,
  normalizeProps: Ae,
  normalizeStyle: Be,
  onActivated: Ne,
  onBeforeMount: Oe,
  onBeforeUnmount: He,
  onBeforeUpdate: Ie,
  onDeactivated: Ue,
  onErrorCaptured: be,
  onMounted: ze,
  onRenderTracked: Fe,
  onRenderTriggered: Ke,
  onScopeDispose: We,
  onServerPrefetch: je,
  onUnmounted: qe,
  onUpdated: Ge,
  onWatcherCleanup: Le,
  openBlock: Qe,
  patchProp: Je,
  popScopeId: Xe,
  provide: Ye,
  proxyRefs: Ze,
  pushScopeId: _e,
  queuePostFlushCb: $e,
  reactive: et,
  readonly: tt,
  ref: ot,
  registerRuntimeCompiler: rt,
  render: nt,
  renderList: st,
  renderSlot: it,
  resolveComponent: at,
  resolveDirective: ct,
  resolveDynamicComponent: lt,
  resolveFilter: dt,
  resolveTransitionHooks: pt,
  setBlockTracking: mt,
  setTransitionHooks: ut,
  shallowReactive: ft,
  shallowReadonly: ht,
  shallowRef: St,
  ssrContextKey: Rt,
  ssrUtils: yt,
  stop: Ct,
  toDisplayString: vt,
  toHandlerKey: gt,
  toHandlers: Tt,
  toRaw: wt,
  toRef: Et,
  toRefs: xt,
  toValue: Mt,
  transformVNodeArgs: Vt,
  triggerRef: kt,
  unref: Pt,
  useAttrs: Dt,
  useCssModule: At,
  useCssVars: Bt,
  useHost: Nt,
  useId: Ot,
  useModel: Ht,
  useSSRContext: It,
  useShadowRoot: Ut,
  useSlots: bt,
  useTemplateRef: zt,
  useTransitionState: Ft,
  vModelCheckbox: Kt,
  vModelDynamic: Wt,
  vModelRadio: jt,
  vModelSelect: qt,
  vModelText: Gt,
  vShow: Lt,
  version: Qt,
  warn: Jt,
  watch: Xt,
  watchEffect: Yt,
  watchPostEffect: Zt,
  watchSyncEffect: _t,
  withAsyncContext: $t,
  withCtx: eo,
  withDefaults: to,
  withDirectives: oo,
  withKeys: ro,
  withMemo: no,
  withModifiers: so,
  withScopeId: io
} = e;
export {
  t as BaseTransition,
  o as BaseTransitionPropsValidators,
  r as Comment,
  n as EffectScope,
  s as ErrorCodes,
  i as ErrorTypeStrings,
  a as Fragment,
  c as KeepAlive,
  l as ReactiveEffect,
  d as Static,
  p as Suspense,
  m as Teleport,
  u as Text,
  f as TrackOpTypes,
  h as Transition,
  S as TransitionGroup,
  R as TriggerOpTypes,
  y as VueElement,
  C as assertNumber,
  v as callWithAsyncErrorHandling,
  g as callWithErrorHandling,
  T as camelize,
  w as capitalize,
  E as cloneVNode,
  x as compatUtils,
  M as compile,
  V as computed,
  k as createApp,
  P as createBlock,
  D as createCommentVNode,
  A as createElementBlock,
  B as createElementVNode,
  N as createHydrationRenderer,
  O as createPropsRestProxy,
  H as createRenderer,
  I as createSSRApp,
  U as createSlots,
  b as createStaticVNode,
  z as createTextVNode,
  F as createVNode,
  K as customRef,
  W as defineAsyncComponent,
  j as defineComponent,
  q as defineCustomElement,
  G as defineEmits,
  L as defineExpose,
  Q as defineModel,
  J as defineOptions,
  X as defineProps,
  Y as defineSSRCustomElement,
  Z as defineSlots,
  _ as effect,
  $ as effectScope,
  ee as getCurrentInstance,
  te as getCurrentScope,
  oe as getCurrentWatcher,
  re as getTransitionRawChildren,
  ne as guardReactiveProps,
  se as h,
  ie as handleError,
  ae as hasInjectionContext,
  ce as hydrate,
  le as hydrateOnIdle,
  de as hydrateOnInteraction,
  pe as hydrateOnMediaQuery,
  me as hydrateOnVisible,
  ue as initCustomFormatter,
  fe as initDirectivesForSSR,
  he as inject,
  Se as isMemoSame,
  Re as isProxy,
  ye as isReactive,
  Ce as isReadonly,
  ve as isRef,
  ge as isRuntimeOnly,
  Te as isShallow,
  we as isVNode,
  Ee as markRaw,
  xe as mergeDefaults,
  Me as mergeModels,
  Ve as mergeProps,
  ke as nextTick,
  Pe as nodeOps,
  De as normalizeClass,
  Ae as normalizeProps,
  Be as normalizeStyle,
  Ne as onActivated,
  Oe as onBeforeMount,
  He as onBeforeUnmount,
  Ie as onBeforeUpdate,
  Ue as onDeactivated,
  be as onErrorCaptured,
  ze as onMounted,
  Fe as onRenderTracked,
  Ke as onRenderTriggered,
  We as onScopeDispose,
  je as onServerPrefetch,
  qe as onUnmounted,
  Ge as onUpdated,
  Le as onWatcherCleanup,
  Qe as openBlock,
  Je as patchProp,
  Xe as popScopeId,
  Ye as provide,
  Ze as proxyRefs,
  _e as pushScopeId,
  $e as queuePostFlushCb,
  et as reactive,
  tt as readonly,
  ot as ref,
  rt as registerRuntimeCompiler,
  nt as render,
  st as renderList,
  it as renderSlot,
  at as resolveComponent,
  ct as resolveDirective,
  lt as resolveDynamicComponent,
  dt as resolveFilter,
  pt as resolveTransitionHooks,
  mt as setBlockTracking,
  ut as setTransitionHooks,
  ft as shallowReactive,
  ht as shallowReadonly,
  St as shallowRef,
  Rt as ssrContextKey,
  yt as ssrUtils,
  Ct as stop,
  vt as toDisplayString,
  gt as toHandlerKey,
  Tt as toHandlers,
  wt as toRaw,
  Et as toRef,
  xt as toRefs,
  Mt as toValue,
  Vt as transformVNodeArgs,
  kt as triggerRef,
  Pt as unref,
  Dt as useAttrs,
  At as useCssModule,
  Bt as useCssVars,
  Nt as useHost,
  Ot as useId,
  Ht as useModel,
  It as useSSRContext,
  Ut as useShadowRoot,
  bt as useSlots,
  zt as useTemplateRef,
  Ft as useTransitionState,
  Kt as vModelCheckbox,
  Wt as vModelDynamic,
  jt as vModelRadio,
  qt as vModelSelect,
  Gt as vModelText,
  Lt as vShow,
  Qt as version,
  Jt as warn,
  Xt as watch,
  Yt as watchEffect,
  Zt as watchPostEffect,
  _t as watchSyncEffect,
  $t as withAsyncContext,
  eo as withCtx,
  to as withDefaults,
  oo as withDirectives,
  ro as withKeys,
  no as withMemo,
  so as withModifiers,
  io as withScopeId
};
