import { NATIVE } from '../types/global';
import { DefineComponent, PublicProps, SlotsType, VNode } from 'vue';
type C<P, S extends Record<string, (...args: any[]) => VNode[]> = Record<never, never>> = DefineComponent<P, {}, {}, {}, {}, {}, {}, {}, string, PublicProps, Readonly<P>, {}, SlotsType<S>>;
type PanelSlots = {};
type TitleLabelSlots = {};
type TextButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    text?: unknown;
};
type TextButtonProps = TextButtonCustomProps & Partial<NATIVE["TextButton"]>;
type TextButtonSlots = {};
type ButtonCustomProps = {
    defaultSquareButtonStyle?: unknown;
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
};
type ButtonProps = ButtonCustomProps & Partial<NATIVE["Button"]>;
type ButtonSlots = {};
type CancelTextButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    text?: unknown;
};
type CancelTextButtonProps = CancelTextButtonCustomProps & Partial<NATIVE["TextButton"]>;
type CancelTextButtonSlots = {};
type CancelButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    width?: number;
};
type CancelButtonProps = CancelButtonCustomProps & Partial<NATIVE["Button"]>;
type CancelButtonSlots = {};
type SmallSecondaryTextButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    text?: unknown;
};
type SmallSecondaryTextButtonProps = SmallSecondaryTextButtonCustomProps & Partial<NATIVE["TextButton"]>;
type SmallSecondaryTextButtonSlots = {};
type SmallTertiaryTextButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    text?: unknown;
};
type SmallTertiaryTextButtonProps = SmallTertiaryTextButtonCustomProps & Partial<NATIVE["TextButton"]>;
type SmallTertiaryTextButtonSlots = {};
type SecondaryTextButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    text?: unknown;
};
type SecondaryTextButtonProps = SecondaryTextButtonCustomProps & Partial<NATIVE["TextButton"]>;
type SecondaryTextButtonSlots = {};
type SecondaryButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    width?: number;
};
type SecondaryButtonProps = SecondaryButtonCustomProps & Partial<NATIVE["Button"]>;
type SecondaryButtonSlots = {};
type TertiaryTextButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    text?: unknown;
};
type TertiaryTextButtonProps = TertiaryTextButtonCustomProps & Partial<NATIVE["TextButton"]>;
type TertiaryTextButtonSlots = {};
type TertiaryButtonCustomProps = {
    sounds?: {};
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
    width?: number;
};
type TertiaryButtonProps = TertiaryButtonCustomProps & Partial<NATIVE["Button"]>;
type TertiaryButtonSlots = {};
type CloseButtonSlots = {};
type CheckBoxSlots = {};
type CheckBoxWithLabelCustomProps = {
    checked?: boolean;
    text?: unknown;
};
type CheckBoxWithLabelProps = CheckBoxWithLabelCustomProps & Partial<NATIVE["Group"]>;
type CheckBoxWithLabelSlots = {};
type TextFieldCustomProps = {
    anchor?: {};
};
type TextFieldProps = TextFieldCustomProps & Partial<NATIVE["TextField"]>;
type TextFieldSlots = {};
type NumberFieldCustomProps = {
    anchor?: {};
};
type NumberFieldProps = NumberFieldCustomProps & Partial<NATIVE["NumberField"]>;
type NumberFieldSlots = {};
type DropdownBoxCustomProps = {
    anchor?: {};
};
type DropdownBoxProps = DropdownBoxCustomProps & Partial<NATIVE["DropdownBox"]>;
type DropdownBoxSlots = {};
type ContentSeparatorCustomProps = {
    anchor?: {
        Bottom?: number;
        Full?: number;
        Height?: number;
        Horizontal?: number;
        Left?: number;
        MaxWidth?: number;
        MinWidth?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
        Width?: number;
    };
};
type ContentSeparatorProps = ContentSeparatorCustomProps & Partial<NATIVE["Group"]>;
type ContentSeparatorSlots = {};
type DefaultSpinnerCustomProps = {
    anchor?: {};
};
type DefaultSpinnerProps = DefaultSpinnerCustomProps & Partial<NATIVE["Sprite"]>;
type DefaultSpinnerSlots = {};
type ActionButtonContainerSlots = {};
type ActionButtonSeparatorSlots = {};
type VerticalActionButtonSeparatorSlots = {};
type SubtitleCustomProps = {
    text?: unknown;
};
type SubtitleProps = SubtitleCustomProps & Partial<NATIVE["Label"]>;
type SubtitleSlots = {};
type TitleCustomProps = {
    alignment?: string;
    text?: string;
};
type TitleProps = TitleCustomProps & Partial<NATIVE["Label"]>;
type TitleSlots = {};
type HeaderSearchCustomProps = {
    marginRight?: number;
};
type HeaderSearchProps = HeaderSearchCustomProps & Partial<NATIVE["Group"]>;
type HeaderSearchSlots = {};
type HeaderTextButtonSlots = {};
type HeaderSeparatorSlots = {};
type PanelTitleCustomProps = {
    alignment?: string;
    text?: string;
};
type PanelTitleProps = PanelTitleCustomProps & Partial<NATIVE["Group"]>;
type PanelTitleSlots = {};
type VerticalSeparatorSlots = {};
type PanelSeparatorFancyCustomProps = {
    anchor?: {};
};
type PanelSeparatorFancyProps = PanelSeparatorFancyCustomProps & Partial<NATIVE["Group"]>;
type PanelSeparatorFancySlots = {};
type ContainerCustomProps = {
    contentPadding?: {
        Bottom?: number;
        Full?: number;
        Horizontal?: number;
        Left?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
    };
    closeButton?: boolean;
};
type ContainerProps = ContainerCustomProps & Partial<NATIVE["Group"]>;
type ContainerSlots = {
    closeButton?: () => VNode[];
    content?: () => VNode[];
    title?: () => VNode[];
};
type DecoratedContainerCustomProps = {
    contentPadding?: {
        Bottom?: number;
        Full?: number;
        Horizontal?: number;
        Left?: number;
        Right?: number;
        Top?: number;
        Vertical?: number;
    };
    closeButton?: boolean;
};
type DecoratedContainerProps = DecoratedContainerCustomProps & Partial<NATIVE["Group"]>;
type DecoratedContainerSlots = {
    closeButton?: () => VNode[];
    content?: () => VNode[];
    title?: () => VNode[];
};
type PageOverlaySlots = {};
type BackButtonSlots = {};
export declare const Common: {
    Panel: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, PanelSlots>;
    TitleLabel: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        elStyle?: import('../types/global').LabelStyle;
        text?: string;
        textSpans?: Array<import('../types/global').LabelSpan>;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, TitleLabelSlots>;
    TextButton: C<TextButtonProps, TextButtonSlots>;
    Button: C<ButtonProps, ButtonSlots>;
    CancelTextButton: C<CancelTextButtonProps, CancelTextButtonSlots>;
    CancelButton: C<CancelButtonProps, CancelButtonSlots>;
    SmallSecondaryTextButton: C<SmallSecondaryTextButtonProps, SmallSecondaryTextButtonSlots>;
    SmallTertiaryTextButton: C<SmallTertiaryTextButtonProps, SmallTertiaryTextButtonSlots>;
    SecondaryTextButton: C<SecondaryTextButtonProps, SecondaryTextButtonSlots>;
    SecondaryButton: C<SecondaryButtonProps, SecondaryButtonSlots>;
    TertiaryTextButton: C<TertiaryTextButtonProps, TertiaryTextButtonSlots>;
    TertiaryButton: C<TertiaryButtonProps, TertiaryButtonSlots>;
    CloseButton: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        disabled?: boolean;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        elStyle?: import('../types/global').ButtonStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, CloseButtonSlots>;
    CheckBox: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        disabled?: boolean;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        elStyle?: import('../types/global').CheckBoxStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        value?: boolean;
        visible?: boolean;
    }>, CheckBoxSlots>;
    CheckBoxWithLabel: C<CheckBoxWithLabelProps, CheckBoxWithLabelSlots>;
    TextField: C<TextFieldProps, TextFieldSlots>;
    NumberField: C<NumberFieldProps, NumberFieldSlots>;
    DropdownBox: C<DropdownBoxProps, DropdownBoxSlots>;
    ContentSeparator: C<ContentSeparatorProps, ContentSeparatorSlots>;
    DefaultSpinner: C<DefaultSpinnerProps, DefaultSpinnerSlots>;
    ActionButtonContainer: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, ActionButtonContainerSlots>;
    ActionButtonSeparator: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, ActionButtonSeparatorSlots>;
    VerticalActionButtonSeparator: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, VerticalActionButtonSeparatorSlots>;
    Subtitle: C<SubtitleProps, SubtitleSlots>;
    Title: C<TitleProps, TitleSlots>;
    HeaderSearch: C<HeaderSearchProps, HeaderSearchSlots>;
    HeaderTextButton: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        disabled?: boolean;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        elStyle?: import('../types/global').TextButtonStyle;
        text?: string;
        textSpans?: Array<import('../types/global').LabelSpan>;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, HeaderTextButtonSlots>;
    HeaderSeparator: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, HeaderSeparatorSlots>;
    PanelTitle: C<PanelTitleProps, PanelTitleSlots>;
    VerticalSeparator: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, VerticalSeparatorSlots>;
    PanelSeparatorFancy: C<PanelSeparatorFancyProps, PanelSeparatorFancySlots>;
    Container: C<ContainerProps, ContainerSlots>;
    DecoratedContainer: C<DecoratedContainerProps, DecoratedContainerSlots>;
    PageOverlay: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, PageOverlaySlots>;
    BackButton: C<Partial<{
        anchor?: import('../types/global').Anchor;
        autoScrollDown?: boolean;
        background?: import('../types/global').PatchStyle | string;
        contentHeight?: number;
        contentWidth?: number;
        flexWeight?: number;
        hitTestVisible?: boolean;
        keepScrollPosition?: boolean;
        layoutMode?: import('../types/global').LayoutMode;
        maskTexturePath?: string;
        mouseWheelScrollBehaviour?: import('../types/global').MouseWheelScrollBehaviourType;
        outlineColor?: string;
        outlineSize?: number;
        overscroll?: boolean;
        padding?: import('../types/global').Padding;
        scrollbarStyle?: import('../types/global').ScrollbarStyle;
        textTooltipShowDelay?: number;
        textTooltipStyle?: import('../types/global').TextTooltipStyle;
        tooltipText?: string;
        tooltipTextSpans?: Array<import('../types/global').LabelSpan>;
        visible?: boolean;
    }>, BackButtonSlots>;
};
export {};
